- <h1 align="center"> Hi 👋, I'm Abhishek Singh Rautela</h1>
<h3 align = "centre">I'm Abhishek Singh Rautela Hello! I am a dedicated computer science undergraduate passionate about programming, full-stack web development, and event management. I am eager to bring my skills and enthusiasm to a top company in the industry. With a strong work ethic, team-building abilities, and excellent communication skills, I am ready to contribute to a dynamic and innovative team. Let's connect and explore potential opportunities together!</h3> 
-<p align="left">

👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
geekabhishekrautela/geekabhishekrautela is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
---> 
